# application: plfapp
runtime: python
# vm: true
env: flex
entrypoint: gunicorn -b :$PORT main:app
# api_version: 1
# threadsafe: true


runtime_config:
  python_version : 3

# handlers:

# - url: /
#   script: main.APP
  # script: auto

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# handlers:
# - url: /
#   script: timesheet_collection.app

# - url: /
#   static_files: plfapp/index.html
#   upload: plfapp/index.html

# - url: /(.*)
#   static_files: plfapp/\1
#   upload: plfapp/(.*)

# - url: /templates
#   static_dir: templates
# - url: /.*
#   script: timesheet_collection.app
  
# libraries:
#   - name: ssl
#     version: latest

